### ISSUE TITLE
401 Unauthorized on /api/v6/users/@me with OAuth.getUser()

### ISSUE THREAD

**Issue by jackmerrill** [reboxer/discord-oauth2#26]
I am trying to make a custom "is the user logged in" function, its as follows:
```js
function checkLogin(req) {
  var token = getcookie("token", req)
  console.log("TOKEN: "+token)
  if (token === 'none') {
    return false
  }
  else {
    var user = oauth.getUser(token)
    if (!user.id) {
      return false
    }
    else {
      return true
    }
  }
}
```

The `getcookie()` function is another custom function since `req.cookies` never worked. It still gets the right cookie and it works as it should. 

I get `UnhandledPromiseRejectionWarning: DiscordHTTPError: 401 Unauthorized on GET /api/v6/users/@me` on line 35, or `var user = oauth.getUser(token)`. Logging the cookie value shows the correct cookie value, so that isn't the issue.

I'm setting the cookie like this:
```js
router.use('/return', async (req, res) => {
  var code = req.query.code
  var token = oauth.tokenRequest({
    code: code,
    grantType: "authorization_code",
    scope: ["identify", "guilds"],
  })
  res.cookie('token', (await token).access_token, { maxAge: 604800000 })
  res.send('<meta http-equiv = "refresh" content = "0; url = /dash" />')
})
```
The `res.send()` is there for a redirect to set the cookie, as `res.redirect()` didn't set the cookie. 

I can't see what I am doing wrong. Any and all help is appreciated. Thanks!

**Comment by reboxer** [comment]
You should never use cookies or a browser to store any kind of credentials (like tokens), this is not supposed to be kept client side and you should use a session cookie to keep this information on the server side (see the package [express-session](https://www.npmjs.com/package/express-session)), and the cookie might be getting modified by the browser because it may be using a different encoding.

```js
  var token = oauth.tokenRequest({
    code: code,
    grantType: "authorization_code",
    scope: ["identify", "guilds"],
  })
  res.cookie('token', (await token).access_token, { maxAge: 604800000 })
```
You shouldn't do this, as if the request fails, your code will throw an error and won't set the correct thing (shouldn't even finish the request). You should catch the error and send the user a proper response.

With the code you provided i can't really find out what is going on, so a repository with a working example of what you are doing would be pretty helpful.
