### ISSUE TITLE
Infinite retry attempts

### ISSUE THREAD

**Issue by demipixel** [reboxer/discord-oauth2#73]
On error 502 there's suppose to be only 3 retry attempts. However, I recently saw that I had some requests that had, like, 100+ web requests for `https://discordapp.com/api/v7/users/@me`, which all resulted in error 502. My theory is that the issue is:

`attempts` is assigned at the top of `request()`
https://github.com/reboxer/discord-oauth2/blob/973bccb626757c946809f71433fc45051df6b88c/lib/eris/rest/RequestHandler.js#L87

Later, on 502, `attempts` is incremented, however we simply call `this.request()` recursively, which in itself initializes `attempts` to 0.
https://github.com/reboxer/discord-oauth2/blob/973bccb626757c946809f71433fc45051df6b88c/lib/eris/rest/RequestHandler.js#L224-L228

Ideally, `request` should take an additional argument `attempts=0` rather that initializing it each time in the function.

**Comment by reboxer** [comment]
Thanks for bringing this up. This seems to be an issue on how the requestHandler was made in Eris which seems to not keep track of the amount of times it tried to send a request and actually does nothing with it, i guess no one has had an issue with it as no one has brought that up.
There have been a bunch of commits made to the requestHandler since i last looked at it, and v8 of the api was released too, i'll have to take a look at them and cherry pick the ones needed to keep it up to date.

**Comment by reboxer** [comment]
Fixed as of 2.10.0
