### ISSUE TITLE
Timeout integer limit

### ISSUE THREAD

**Issue by jimnordb** [reboxer/discord-oauth2#89]
**Describe the error**
Gateway 504 error. It was only thrown towards the /api/discord endpoint i had setup for this oauth module. rest of the routes worked fine in express. Had to do a restart of service to make it work again. Hardly any debug details so i am sorry about that.

users are doing discord auths about every 1-2 seconds

**NodeJS version**
v14.20.0

**Library version**
2.10.0

**Error stack and exact error message**
2022-11-09T12:04:28: Timeout duration was set to 1.
2022-11-09T12:04:28: (node:1713608) TimeoutOverflowWarning: 18446744073673216000 does not fit into a 32-bit signed integer.

*The error stack thrown by the library and the exact error message sent by discord (see [debugging](https://github.com/reboxer/discord-oauth2#debugging))

**Relevant code**
```js
// Put here the code you are using that is not working
```

**Comment by reboxer** [comment]
This might have happened because of the 504 (something that doesn't happen often) returning some strange value and without knowing the exact request and response there is no way to debug this, so there's not much we can do here. Though i don't think this has to do with the 504 error at all, as an error like that wouldn't return any header discord uses for rate limiting and that number is ridiculously big, so this could have originated from somewhere else in your code where you use a `setTimeout`.
